var searchData=
[
  ['player_20id_0',['Data | player id *|',['../classClientLobby.html#autotoc_md1',1,'']]],
  ['player_20id_20new_20handicap_1',['Data | local player id | new handicap |',['../classServerLobby.html#autotoc_md9',1,'']]],
  ['prop_5falign_2',['PROP_ALIGN',['../gui_overview.html#prop12',1,'']]],
  ['prop_5fchild_5fheight_3',['PROP_CHILD_WIDTH, PROP_CHILD_HEIGHT',['../gui_overview.html#prop10',1,'']]],
  ['prop_5fchild_5fwidth_20prop_5fchild_5fheight_4',['PROP_CHILD_WIDTH, PROP_CHILD_HEIGHT',['../gui_overview.html#prop10',1,'']]],
  ['prop_5fcolor_5fslider_5',['PROP_COLOR_SLIDER',['../gui_overview.html#prop21',1,'']]],
  ['prop_5fdiv_5fpadding_6',['PROP_DIV_PADDING',['../gui_overview.html#prop19',1,'']]],
  ['prop_5fextend_5flabel_7',['PROP_EXTEND_LABEL',['../gui_overview.html#prop15',1,'']]],
  ['prop_5fheight_8',['PROP_WIDTH, PROP_HEIGHT',['../gui_overview.html#prop8',1,'']]],
  ['prop_5ficon_9',['PROP_ICON',['../gui_overview.html#prop3',1,'']]],
  ['prop_5fid_10',['PROP_ID',['../gui_overview.html#prop1',1,'']]],
  ['prop_5fkeep_5fselection_11',['PROP_KEEP_SELECTION',['../gui_overview.html#prop20',1,'']]],
  ['prop_5flabels_5flocation_12',['PROP_LABELS_LOCATION',['../gui_overview.html#prop16',1,'']]],
  ['prop_5flayout_13',['PROP_LAYOUT',['../gui_overview.html#prop11',1,'']]],
  ['prop_5fmax_5fheight_14',['PROP_MAX_WIDTH, PROP_MAX_HEIGHT',['../gui_overview.html#prop9',1,'']]],
  ['prop_5fmax_5frows_15',['PROP_MAX_ROWS',['../gui_overview.html#prop17',1,'']]],
  ['prop_5fmax_5fvalue_16',['PROP_MIN_VALUE, PROP_MAX_VALUE',['../gui_overview.html#prop6',1,'']]],
  ['prop_5fmax_5fwidth_20prop_5fmax_5fheight_17',['PROP_MAX_WIDTH, PROP_MAX_HEIGHT',['../gui_overview.html#prop9',1,'']]],
  ['prop_5fmin_5fvalue_20prop_5fmax_5fvalue_18',['PROP_MIN_VALUE, PROP_MAX_VALUE',['../gui_overview.html#prop6',1,'']]],
  ['prop_5fproportion_19',['PROP_PROPORTION',['../gui_overview.html#prop13',1,'']]],
  ['prop_5fsquare_20',['PROP_SQUARE',['../gui_overview.html#prop14',1,'']]],
  ['prop_5ftext_21',['PROP_TEXT',['../gui_overview.html#prop2',1,'']]],
  ['prop_5ftext_5falign_20prop_5ftext_5fvalign_22',['PROP_TEXT_ALIGN, PROP_TEXT_VALIGN',['../gui_overview.html#prop4',1,'']]],
  ['prop_5ftext_5fvalign_23',['PROP_TEXT_ALIGN, PROP_TEXT_VALIGN',['../gui_overview.html#prop4',1,'']]],
  ['prop_5fwidth_20prop_5fheight_24',['PROP_WIDTH, PROP_HEIGHT',['../gui_overview.html#prop8',1,'']]],
  ['prop_5fword_5fwrap_25',['PROP_WORD_WRAP',['../gui_overview.html#prop5',1,'']]],
  ['prop_5fwrap_5faround_26',['PROP_WRAP_AROUND',['../gui_overview.html#prop18',1,'']]],
  ['prop_5fx_20prop_5fy_27',['PROP_X, PROP_Y',['../gui_overview.html#prop7',1,'']]],
  ['prop_5fy_28',['PROP_X, PROP_Y',['../gui_overview.html#prop7',1,'']]],
  ['properties_29',['Properties',['../gui_overview.html#props',1,'']]]
];
